# This workflow will sign an installer for the PcPatr-FLEx utility.

name: PcPatr-FLEx Sign and Release

on:
  push:
    paths:
      - 'Installer/Output/**'
      - '.github/workflows/pcpatr**.yml'
jobs:
  preparation:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: PcPatrFLEx
          path: Installer/Output/UsePcPatrWithFLExDllSetup.exe
          if-no-files-found: error

  sign-installer:
    name: Sign PcPatrFLEx installer
    needs: preparation
    uses: sillsdev/codesign/.github/workflows/sign.yml@v2
    with:
      artifact: PcPatrFLEx
    secrets:
      certificate: ${{ secrets.CODESIGN_LSDEVSECTIGOEV }}

  create-release:
    name: Create Release
    needs: sign-installer
    runs-on: windows-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: PcPatrFLEx

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: UsePcPatrWithFLExDllSetup.exe
          body: |
            Release for version ${{ github.ref }}
          draft: true
