copy "..\PcPatrFLExDll\bin\x64\Release\pcpatr64.exe" "c:\fwrepo\fw\Output\Release"
copy "..\PcPatrFLExDll\bin\x64\Release\LingTreeTree.dll" "c:\fwrepo\fw\Output\Release"
copy "..\PcPatrFLExDll\bin\x64\Release\PcPatrFLExDll.dll" "c:\fwrepo\fw\Output\Release"
copy "..\PcPatrFLExDll\bin\x64\Release\PcPatrFLExDll.pdb" "c:\fwrepo\fw\Output\Release"
copy "..\PcPatrFLExDll\bin\x64\Release\PrepFLExDBDll.dll" "c:\fwrepo\fw\Output\Release"
copy "..\PcPatrFLExDll\bin\x64\Release\PrepFLExDBDll.pdb" "c:\fwrepo\fw\Output\Release"
copy "..\PcPatrFLExDll\bin\x64\Release\SIL.DisambiguateInFLExDB.dll" "c:\fwrepo\fw\Output\Release"
copy "..\PcPatrFLExDll\bin\x64\Release\SIL.DisambiguateInFLExDB.pdb" "c:\fwrepo\fw\Output\Release"
copy "..\PcPatrBrowser\PcPatrBrowserDll\bin\x64\Release\SIL.PcPatrBrowserDll.dll" "c:\fwrepo\fw\Output\Release"
copy "..\PcPatrBrowser\PcPatrBrowserDll\bin\x64\Release\SIL.PcPatrBrowserDll.pdb" "c:\fwrepo\fw\Output\Release"
mkdir "c:\fwrepo\fw\Output\Release\Transforms"
copy "..\PcPatrFLExDll\bin\Transforms\InitFeature.htm" "c:\fwrepo\fw\Output\Release\Transforms"
copy "..\PcPatrFLExDll\bin\Transforms\InitInterlinear.htm" "c:\fwrepo\fw\Output\Release\Transforms"
copy "..\PcPatrFLExDll\bin\Transforms\NoInterlinear.htm" "c:\fwrepo\fw\Output\Release\Transforms"
copy "..\PcPatrFLExDll\bin\Transforms\PcPatrToLingTree.xsl" "c:\fwrepo\fw\Output\Release\Transforms"
copy "..\PcPatrFLExDll\bin\Transforms\ShowFS.xsl" "c:\fwrepo\fw\Output\Release\Transforms"
copy "..\PcPatrFLExDll\bin\Transforms\ShowInterlinear.xsl" "c:\fwrepo\fw\Output\Release\Transforms"
copy "..\PcPatrFLExDll\doc\pcpatr.html" "c:\fwrepo\fw\Output\Release\doc"
copy "..\PcPatrFLExDll\doc\UserDocumentation.pdf" "c:\fwrepo\fw\Output\Release\doc"

REM copy "C:\fwrepo\fw\DistFiles\Language Explorer\Configuration\UtilityCatalogInclude.xml" "C:\fwrepo\fw\DistFiles\Language Explorer\Configuration\UtilityCatalogIncludeOrig.xml"
REM copy UtilityCatalogLine.txt >> "C:\fwrepo\fw\DistFiles\Language Explorer\Configuration\UtilityCatalogInclude.xml"

