copy "..\PcPatrFLExDll\bin\x64\Debug\pcpatr64.exe" "c:\fwrepo\fw\Output\Debug"
copy "..\PcPatrFLExDll\bin\x64\Debug\LingTreeTree.dll" "c:\fwrepo\fw\Output\Debug"
copy "..\PcPatrFLExDll\bin\x64\Debug\PcPatrFLExDll.dll" "c:\fwrepo\fw\Output\Debug"
copy "..\PcPatrFLExDll\bin\x64\Debug\PcPatrFLExDll.pdb" "c:\fwrepo\fw\Output\Debug"
copy "..\PcPatrFLExDll\bin\x64\Debug\PrepFLExDB.exe" "c:\fwrepo\fw\Output\Debug"
copy "..\PcPatrFLExDll\bin\x64\Debug\PrepFLExDB.pdb" "c:\fwrepo\fw\Output\Debug"
copy "..\PcPatrFLExDll\bin\x64\Debug\SIL.DisambiguateInFLExDB.dll" "c:\fwrepo\fw\Output\Debug"
copy "..\PcPatrFLExDll\bin\x64\Debug\SIL.DisambiguateInFLExDB.pdb" "c:\fwrepo\fw\Output\Debug"
copy "..\PcPatrBrowser\PcPatrBrowserDll\bin\x64\Debug\SIL.PcPatrBrowserDll.dll" "c:\fwrepo\fw\Output\Debug"
copy "..\PcPatrBrowser\PcPatrBrowserDll\bin\x64\Debug\SIL.PcPatrBrowserDll.pdb" "c:\fwrepo\fw\Output\Debug"
mkdir "c:\fwrepo\fw\Output\Debug\Transforms"
copy "..\PcPatrFLExDll\bin\Transforms\InitFeature.htm" "c:\fwrepo\fw\Output\Debug\Transforms"
copy "..\PcPatrFLExDll\bin\Transforms\InitInterlinear.htm" "c:\fwrepo\fw\Output\Debug\Transforms"
copy "..\PcPatrFLExDll\bin\Transforms\NoInterlinear.htm" "c:\fwrepo\fw\Output\Debug\Transforms"
copy "..\PcPatrFLExDll\bin\Transforms\PcPatrToLingTree.xsl" "c:\fwrepo\fw\Output\Debug\Transforms"
copy "..\PcPatrFLExDll\bin\Transforms\ShowFS.xsl" "c:\fwrepo\fw\Output\Debug\Transforms"
copy "..\PcPatrFLExDll\bin\Transforms\ShowInterlinear.xsl" "c:\fwrepo\fw\Output\Debug\Transforms"
copy "..\PcPatrFLExDll\doc\pcpatr.html" "c:\fwrepo\fw\Output\Debug\doc"
copy "..\PcPatrFLExDll\doc\UserDocumentation.pdf" "c:\fwrepo\fw\Output\Debug\doc"

REM copy "C:\fwrepo\fw\DistFiles\Language Explorer\Configuration\UtilityCatalogInclude.xml" "C:\fwrepo\fw\DistFiles\Language Explorer\Configuration\UtilityCatalogIncludeOrig.xml"
REM copy UtilityCatalogLine.txt >> "C:\fwrepo\fw\DistFiles\Language Explorer\Configuration\UtilityCatalogInclude.xml"

